[features]
resolution = true
skip-lint = false

[programs.localnet]
dephy_id = "6RuNPDwj63gfBFEx7DFfoQPbxfkDHQt4ccf8d4eWAZDX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run -b ts-mocha ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 3000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/fixtures/mpl_core.so"
